[package]
name = "rust-visualisation"
version = "0.1.0"
authors = ["Diez B. Roggisch <deets@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.13.1"
nanomsg = "0.7.2"
ringbuf = "0.2.1"
